stages:
 - deploy

deploy_firebase:
  stage: deploy
  image: node:latest
  script:
      - npm install
      - npm install -g firebase-tools
      - firebase --token 1//04Gy44CZpqwx4CgYIARAAGAQSNwF-L9IrJzzhGBzLh1DWJMF1voIvxhfbZhO0nW1fODAleKhbm3pFbR4osaFtvnBJCaz1oPnF_6I functions:config:get > functions/env.json
      - CI="" npm run prestart
      - cd functions/
      - npm install
      - cd ..
      - firebase use --token 1//04Gy44CZpqwx4CgYIARAAGAQSNwF-L9IrJzzhGBzLh1DWJMF1voIvxhfbZhO0nW1fODAleKhbm3pFbR4osaFtvnBJCaz1oPnF_6I default
      - firebase --token 1//04Gy44CZpqwx4CgYIARAAGAQSNwF-L9IrJzzhGBzLh1DWJMF1voIvxhfbZhO0nW1fODAleKhbm3pFbR4osaFtvnBJCaz1oPnF_6I deploy --non-interactive