stages:
 - deploy

deploy_firebase:
  stage: deploy
  image: node:latest
  script:
      - npm install
      - npm install -g firebase-tools
      - firebase functions:config:get
      - npm run prestart
      - cd functions/
      - npm install
      - cd ..
      - echo "Deploying..."
      - firebase deploy --token ${FIREBASE_TOKEN}