stages:
 - deploy

deploy_firebase:
  stage: deploy
  image: node:latest
  script:
      - npm install
      - npm install -g firebase-tools
      - firebase --token $FIREBASE_TOKEN functions:config:get > functions/env.json
      - CI="" npm run prestart
      - cd functions/
      - npm install
      - cd ..
      - firebase use --token $FIREBASE_TOKEN default
      - firebase --token $FIREBASE_TOKEN deploy --non-interactive
