stages:
 - deploy

deploy_firebase:
  stage: deploy
  image: node:latest
  before_script:
      - npm install
      - npm install -g firebase-tools
      - cd functions/
      - npm install
  script:
      - echo "Deploying..."
      - firebase functions:config:get > functions/env.json
      - firebase deploy --token ${FIREBASE_TOKEN}